### ISSUE TITLE
Project won't compile!

### ISSUE THREAD

**Issue by Yoshimaster96** [Ploaj/ArcCross#13]
When trying to open the project, I get this strange popup:
![Capture50](https://user-images.githubusercontent.com/15160568/64501688-fb4c2480-d287-11e9-9b44-6be9ce5c6d1b.PNG)

And when I compile, I get this error:
`The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks`

I'm using the latest version of Visual Studio 2019.

**Comment by M-1-RLG** [comment]
Download the .NET Framework Developer Pack here: https://dotnet.microsoft.com/download/thank-you/net461-developer-pack
