### ISSUE TITLE
IndexOutOfRangeException when extracting regional files due to initial index value

### ISSUE THREAD

**Issue by ScanMountGoat** [Ploaj/ArcCross#2]
https://github.com/Ploaj/ArcCross/blob/f5a2e67721ec7897ed584f60a9a4a5f547901e75/CrossArc/Form1.cs#L270

Unless a regional file is selected, there isn't a way to set the value.

**Comment by Ploaj** [comment]
defaulted to 0 = (Japanese) in the latest commit
