### ISSUE TITLE
Issue with Regional and Music Extracting

### ISSUE THREAD

**Issue by Kurausukun** [Ploaj/ArcCross#3]
When I try to extract character voices with "language to extract" set to Japanese, some files fail to extract. For example, the base Bayonetta and Bayonetta c00 voice will not extract. However, they will extract if I manually "extract compressed," but I don't actually know how to decompress them.

Additionally, music extraction seems to not work at all... it just sits at an empty bar and says "Extracting" forever.

**Comment by Ploaj** [comment]
By "fail to extract" do you mean that there is an error or the file is just not exported?

You can decompress them manually with this:
https://github.com/facebook/zstd

Music extraction was never finished, but there are other tools that can export the music out there.

**Comment by Kurausukun** [comment]
Thanks for linking that. I'm not sure if the program gives an actual error when trying to extract it because the window disappears immediately, but no file is extracted at all when you try. As I said last time, this affects a lot of files, but I've been using Bayonetta's default and c00 voices for testing.
